### ISSUE TITLE
some trouble in pytorch 0.4.0

### ISSUE THREAD

**Issue by wang1104014663** [lzrobots/LearningToCompare_ZSL#1]
when I run awa1.py
there are some question.

File "E:/deeplearning/LearningToCompare_ZSL-master/AwA1_RN.py", line 256, in <listcomp>
    rewards = [1 if predict_labels[j]==re_batch_labels[j] else 0 for j in range(batch_size)]
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #2 'other'

**Comment by aditya-jonnalagadda** [comment]
Hi, you just need to modify the variable to be compatible with CUDA

-                    re_batch_labels = torch.LongTensor(re_batch_labels)
+                    re_batch_labels = torch.LongTensor(re_batch_labels).cuda(GPU)


Thanks
