### ISSUE TITLE
Performance on AwA1

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [lzrobots/LearningToCompare_ZSL#2]
Hi, I ran the default code to get the performance on AwA1. I got the following performance which is not as good as reported in the paper.

zsl: 0.6668425681618294
gzsl: seen=0.9183, unseen=0.1810, h=0.3024
save networks for episode: 45999

Can you please let me know what parameters needs to be used in order the get the performance you reported in the paper?

Thanks

**Comment by hawklucky** [comment]
@aditya-jonnalagadda I also have problems to reproduce the results, have you fixed it yet?

**Comment by lzrobots** [comment]
@aditya-jonnalagadda @hawklucky Hi Both, please use early stopping in this demo code. The performances are already printed.
