### ISSUE TITLE
about test part

### ISSUE THREAD

**Issue by wang1104014663** [lzrobots/LearningToCompare_ZSL#3]
Thank you for sharing the code. However, in the part of calculating the accuracy rate, the accuracy of each class should be used, and then the category average should be obtained instead of the accuracy of all images.This compares to the accuracy data you quoted.

**Comment by lzrobots** [comment]
@wang1104014663 Thanks for pointing out. It seems we released the old evaluation protocol version -- "top1 over all samples", as used in table 3.  We revise it to "averaged per class accuracy" now. Thanks again.
