### ISSUE TITLE
The accuracy of AwA

### ISSUE THREAD

**Issue by Linjingkai** [lzrobots/LearningToCompare_ZSL#7]
I am sorry that I cannot get similar accuracy of the paper using  files AwA1.py and AwA2.py.  The gzsl_unseen_accuracy I do can only get 20% or a little more.  Could you place share the pkl files about zsl_awa2_relation_network_v33.pkl, zsl_awa2_attribute_network_v33.pkl, zsl_awa1_relation_network_v33.pkl, zsl_awa1_attribute_network_v33.pkl?

Thank you!

**Comment by LevelCA** [comment]
The result like to yours. what the reason for this problem ？

**Comment by Linjingkai** [comment]
There used to be somethong wrong about my project. I've got it. Thank you!
